name: ARM64 Build via QEMU
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker run --rm -t arm64v8/ubuntu uname -m
      - uses: actions/checkout@v2
      - run: docker build --platform linux/arm64/v8 . -t test
      - run: docker run test
